name: deployment

on:
  push:
    branches: [ "test" ]
  
jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build page
      run: npm run build:prod
    - name: Deploy app to GitHub Pages
      uses: lr0pb/deploy-pages@v1
      id: deployment
      with:
        node-version: 18.x
        build-comand: 'build'
        output-dir: 'dist'
